-- УДАЛЕНИЕ СУЩЕСТВУЮЩИХ ТАБЛИЦ (для чистого запуска, опционально)
DROP TABLE IF EXISTS compilations_events;
DROP TABLE IF EXISTS participation_requests;
DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS compilations;
DROP TABLE IF EXISTS locations;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS users;

-- 1. ТАБЛИЦА ПОЛЬЗОВАТЕЛЕЙ (users)
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(254) NOT NULL UNIQUE, -- Уникальный email, длина до 254
    name VARCHAR(250) NOT NULL         -- Имя пользователя, длина до 250
);

-- 2. ТАБЛИЦА КАТЕГОРИЙ (categories)
CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE   -- Уникальное название категории, длина до 50
);

-- 3. ТАБЛИЦА ЛОКАЦИЙ (locations)
CREATE TABLE IF NOT EXISTS locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lat FLOAT NOT NULL,                -- Широта
    lon FLOAT NOT NULL                 -- Долгота
    -- Примечание: можно добавить UNIQUE INDEX на (lat, lon) если нужно избегать дубликатов координат
);

-- 4. ТАБЛИЦА СОБЫТИЙ (events)
CREATE TABLE IF NOT EXISTS events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    annotation VARCHAR(2000) NOT NULL,
    category_id BIGINT NOT NULL REFERENCES categories(id) ON DELETE RESTRICT, -- Связь с категориями
    created_on TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    description VARCHAR(7000) NOT NULL,
    event_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    initiator_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,    -- Связь с пользователями (инициаторами)
    location_id BIGINT NOT NULL REFERENCES locations(id) ON DELETE CASCADE, -- Связь с локациями
    paid BOOLEAN NOT NULL DEFAULT FALSE,
    participant_limit INTEGER NOT NULL DEFAULT 0,
    published_on TIMESTAMP WITHOUT TIME ZONE,
    request_moderation BOOLEAN NOT NULL DEFAULT TRUE,
    state VARCHAR(50) NOT NULL,         -- Статус события (PENDING, PUBLISHED, CANCELED)
    title VARCHAR(120) NOT NULL
    -- views и confirmed_requests обычно не хранятся в основной таблице событий, а вычисляются/отслеживаются отдельно
);

-- 5. ТАБЛИЦА ЗАЯВОК НА УЧАСТИЕ (participation_requests)
CREATE TABLE IF NOT EXISTS participation_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    event_id BIGINT NOT NULL REFERENCES events(id) ON DELETE CASCADE,     -- ID события
    requester_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE, -- ID пользователя, подавшего заявку
    status VARCHAR(50) NOT NULL                                         -- Статус заявки (PENDING, APPROVED, REJECTED, CANCELED)
);

-- 6. ТАБЛИЦА ПОДБОРОК (compilations)
CREATE TABLE IF NOT EXISTS compilations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pinned BOOLEAN NOT NULL DEFAULT FALSE,
    title VARCHAR(50) NOT NULL
);

-- 7. ПРОМЕЖУТОЧНАЯ ТАБЛИЦА ДЛЯ СВЯЗИ МНОГИЕ-КО-МНОГИМ МЕЖДУ ПОДБОРКАМИ И СОБЫТИЯМИ (compilations_events)
CREATE TABLE IF NOT EXISTS compilations_events (
    compilation_id BIGINT NOT NULL REFERENCES compilations(id) ON DELETE CASCADE,
    event_id BIGINT NOT NULL REFERENCES events(id) ON DELETE CASCADE,
    PRIMARY KEY (compilation_id, event_id) -- Составной первичный ключ обеспечивает уникальность пары
);
